// Alias för vanligaste intents – expandera över tid
export const CONDITION_ALIASES: Record<string,string> = {
  "anxiety":"anxiety",
  "stress":"anxiety",
  "panic":"anxiety",
  "nervous":"anxiety",
  "worried":"anxiety",
  "sleep":"sleep",
  "insomnia":"sleep",
  "sleepless":"sleep",
  "tired":"sleep",
  "digestion":"digestion",
  "ibs":"digestion",
  "bloating":"digestion",
  "stomach":"digestion",
  "gut":"digestion",
  "energy":"energy",
  "fatigue":"energy",
  "tired":"energy",
  "exhausted":"energy",
  "focus":"focus",
  "adhd":"focus",
  "concentration":"focus",
  "memory":"focus",
  "brain":"focus",
  "headache":"headache",
  "migraine":"headache",
  "head":"headache",
  "pain":"pain",
  "inflammation":"inflammation",
  "swelling":"inflammation",
  "immune":"immune",
  "cold":"immune",
  "flu":"immune",
  "sick":"immune",
  "heart":"heart",
  "blood":"heart",
  "pressure":"heart",
  "skin":"skin",
  "acne":"skin",
  "eczema":"skin",
  "psoriasis":"skin",
  "hormone":"hormone",
  "pms":"hormone",
  "menopause":"hormone",
  "thyroid":"hormone",
  "detox":"detox",
  "liver":"detox",
  "cleanse":"detox"
};

// Plantalias (vanliga namn -> slug)
export const PLANT_ALIASES: Record<string,string> = {
  "ashwagandha":"ashwagandha",
  "withania":"ashwagandha",
  "lemon balm":"lemon-balm",
  "melissa":"lemon-balm",
  "rhodiola":"rhodiola",
  "chamomile":"chamomile",
  "matricaria":"chamomile",
  "turmeric":"turmeric",
  "curcumin":"turmeric",
  "tulsi":"holy-basil",
  "holy basil":"holy-basil",
  "passionflower":"passionflower",
  "valerian":"valerian-root",
  "valerian root":"valerian-root",
  "ginseng":"ginseng",
  "echinacea":"echinacea",
  "elderberry":"elderberry",
  "garlic":"garlic",
  "ginger":"ginger",
  "cinnamon":"cinnamon",
  "milk thistle":"milk-thistle",
  "reishi":"reishi",
  "cordyceps":"cordyceps",
  "lions mane":"lions-mane",
  "lion's mane":"lions-mane",
  "bacopa":"bacopa",
  "ginkgo":"ginkgo-biloba",
  "ginkgo biloba":"ginkgo-biloba",
  "maca":"maca",
  "chasteberry":"chasteberry",
  "hawthorn":"hawthorn",
  "hawthorn berry":"hawthorn",
  "marshmallow":"marshmallow-root",
  "marshmallow root":"marshmallow-root",
  "slippery elm":"slippery-elm",
  "licorice":"licorice-root",
  "licorice root":"licorice-root",
  "fennel":"fennel",
  "dandelion":"dandelion-root",
  "dandelion root":"dandelion-root",
  "burdock":"burdock-root",
  "burdock root":"burdock-root",
  "nettle":"nettle",
  "alfalfa":"alfalfa",
  "red clover":"red-clover",
  "triphala":"triphala",
  "chlorella":"chlorella",
  "spirulina":"spirulina",
  "sea moss":"sea-moss",
  "black cohosh":"black-cohosh",
  "dong quai":"dong-quai",
  "wild yam":"wild-yam",
  "shatavari":"shatavari",
  "tribulus":"tribulus",
  "fenugreek":"fenugreek",
  "saw palmetto":"saw-palmetto",
  "cayenne":"cayenne",
  "bilberry":"bilberry",
  "boswellia":"boswellia",
  "devil's claw":"devil-s-claw",
  "white willow":"white-willow",
  "capsaicin":"capsaicin",
  "arnica":"arnica",
  "aloe vera":"aloe-vera",
  "calendula":"calendula",
  "tea tree":"tea-tree",
  "rosehip":"rosehip",
  "jojoba":"jojoba",
  "shea butter":"shea-butter",
  "guarana":"guarana",
  "yerba mate":"yerba-mate",
  "coffee":"coffee"
};
