// AUTOGENERATED
import { Plant } from '../types';

const bacopa: Plant = {
  name: "Bacopa",
  latin: "Bacopa monnieri",
  slug: "bacopa",
  uses: ["Memory Issues", "ADHD", "Brain Fog", "Cognitive Enhancement", "Anxiety"],
  description: "A traditional Ayurvedic herb known as 'Brahmi,' used for centuries to enhance memory, learning, and cognitive function. Contains bacosides that support brain health.",
  preparation: "Capsules, powder, or tincture. Often taken daily for cognitive support.",
  sources: [
    { name: "PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=bacopa+monnieri" },
    { name: "WebMD", url: "https://www.webmd.com/vitamins/ai/ingredientmono-761/bacopa" }
  ],
  category: "Mind",
};

export default bacopa;

