// AUTOGENERATED
import { Plant } from '../types';

const bilberry: Plant = {
  name: "Bilberry",
  latin: "Vaccinium myrtillus",
  slug: "bilberry",
  uses: ["Eye Health", "Night Vision", "Antioxidant", "Circulation", "Diabetes"],
  description: "A close relative of blueberries, bilberry is rich in anthocyanins that support eye health and improve night vision. Used for centuries in European herbal medicine.",
  preparation: "Capsules, powder, or fresh berries. Often taken for eye health support.",
  sources: [
    { name: "PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=vaccinium+myrtillus" },
    { name: "WebMD", url: "https://www.webmd.com/vitamins/ai/ingredientmono-1018/bilberry" }
  ],
  category: "Body",
};

export default bilberry;

