// AUTOGENERATED
import { Plant } from '../types';

const ginkgoBiloba: Plant = {
  name: "Ginkgo Biloba",
  latin: "Ginkgo biloba",
  slug: "ginkgo-biloba",
  uses: ["Memory Issues", "Brain Fog", "ADHD", "Hearing Loss", "Eye Health"],
  description: "One of the oldest living tree species, ginkgo biloba improves blood flow to the brain and supports cognitive function. Used for memory enhancement and mental clarity.",
  preparation: "Capsules, tea, or tincture. Often taken daily for cognitive support.",
  sources: [
    { name: "PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=ginkgo+biloba" },
    { name: "WebMD", url: "https://www.webmd.com/vitamins/ai/ingredientmono-333/ginkgo-biloba" }
  ],
  category: "Mind",
};

export default ginkgoBiloba;

